spring.profiles.active: en

guru:
  username:  laurens-in-english
  password:  password
  dburl: blabla
  jms:
    username:  laurens-in-english-jms
    password:  password-jms
    dburl: blabla-jms


#  3 dashes means new file, in this way you can combine properties yamls in one file
---


spring.profiles.active: es

guru:
  username:  laurens-in-spanish
  password:  password-spanish
  dburl: blabla-spanish
  jms:
    username:  laurens-in-spanish-jms
    password:  password-jms-spanish
    dburl: blabla-jms-spanish
