spring.profiles.active: en

guru:
  username:  laurens-in-english
  password:  password
  dburl: blabla


#  3 dashes means new file, in this way you can combine properties yamls in one file
---


spring.profiles.active: es

guru:
  username:  laurens-in-spanish
  password:  password
  dburl: blabla

